Bug: Revert "Fix the release process issue (#302)" (#321)
This partially reverts commit 7b6eb4a7e6ee6f945d5f3e0a0d6f79054f9518b5
as it's causing a issue with nightly releases.

```bash
In wheel files path:
release/artifacts/tenstorrent/tt-torch/install-artifacts-release/wheels:
tt_torch-0.3.0.dev20250804-cp310-cp310-linux_x86_64.whl

release/artifacts/tenstorrent/tt-torch/install-artifacts/wheels:
tt_torch-0.3.0.dev20250804-cp310-cp310-linux_x86_64.whl
Error: Unable to process file command 'output' successfully.
Error: Invalid format 'release/artifacts/tenstorrent/tt-torch/install-artifacts/wheels'

```


https://github.com/tenstorrent/tt-forge/actions/runs/16715433205/job/47307889406#step:5:670

The issues is caused when both `install-artifacts-release` and
`install-artifacts` is downloaded, both wheels are named
tt_torch-0.1.whl which causes a conflict. We also only want
install-artifacts-release since that doesn't compile with code coverage

```bash
~/work/tt-forge/tt-forge/release/artifacts/tenstorrent/tt-torch/install-artifacts-release/wheels ~/work/tt-forge/tt-forge
Unpacking to: tt_torch-0.1...OK
```

https://github.com/tenstorrent/tt-forge/actions/runs/16641278276/job/47091913390#step:5:580

```bash
~/work/tt-forge/tt-forge/release/artifacts/tenstorrent/tt-torch/install-artifacts/wheels ~/work/tt-forge/tt-forge
Unpacking to: tt_torch-0.1...OK
```

https://github.com/tenstorrent/tt-forge/actions/runs/16641278276/job/47091913390#step:5:605