bug: fix repo arg in annotated tag  (#362)
This bug is caused by not supplying the full repo name for the annotated
tag action, which only affects user-triggered workflow dispatches, e.g.,
([Create Version
Branches](https://github.com/tenstorrent/tt-forge/actions/workflows/create-version-branches.yml)
). Automated releases, such as Nightly releases, are not affected.

```bash
Error: Invalid repository 'tt-torch'. Expected format {owner}/{repo}.
```

https://github.com/tenstorrent/tt-forge/actions/runs/17000074653/job/48202880263#step:8:54

The fix is to use the
[repo_full](https://github.com/tenstorrent/tt-forge/blob/main/.github/actions/set-release-facts/action.yaml#L135)
in set release facts, which is always returns with the full repo name.