bug fix docker build no args & to from doc change log (#268)
Changes:

**Fixed bug when no Docker build opts are supplied.**

```bash
ERROR: docker: 'docker buildx build' requires 1 argument

Usage:  docker buildx build [OPTIONS] PATH | URL | -

Run 'docker buildx build --help' for more information
```

https://github.com/tenstorrent/tt-forge/actions/runs/16268476207/job/45931076160#step:5:285

**Fixed bug that occurred when we bumped our version in for testing
suite** https://github.com/tenstorrent/tt-forge/pull/263

```bash
  if [[ "nightly" == "nightly" ]]; then
    old_version="0.2.0.dev$(date -d "24 hours ago" '+%Y%m%d')"
  fi
 ```
 https://github.com/tenstorrent/tt-forge/actions/runs/16273290240/job/45946147154#step:7:30

**Improve git log generation due to version bump bug**

This closed https://github.com/tenstorrent/tt-forge/issues/269