bug: pin the torch version for tt-torch tests (#377)
### Issue: 

torch was using `2.8.0` instead of `2.7.0`

```bash
  File "/home/forge/.local/lib/python3.10/site-packages/tt_torch/dynamo/experimental/xla_backend.py", line 40, in <module>
    import torch_xla
  File "/home/forge/.local/lib/python3.10/site-packages/torch_xla/__init__.py", line 20, in <module>
    import _XLAC
ImportError: /home/forge/.local/lib/python3.10/site-packages/_XLAC.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZNK3c1010TensorImpl18compute_contiguousENS0_8identityIbEE
```

https://github.com/tenstorrent/tt-forge/actions/runs/17061412802/job/48368863889

```bash
Collecting torch==2.8.0
  Downloading torch-2.8.0-cp310-cp310-manylinux_2_28_x86_64.whl (888.0 MB)
  ```
https://github.com/tenstorrent/tt-forge/actions/runs/17061412802/job/48368863889#step:6:84

### Fix:
Copy the install order from `tt-torch` and that has fixed the issues.
https://github.com/tenstorrent/tt-torch/blob/main/requirements.txt#L3-L4

Ran the nightly test and verified all tt-torch runners were successful.
https://github.com/tenstorrent/tt-forge/actions/runs/17107762523/job/48522713221